### ISSUE TITLE
When updating, make sure the current user has permission to do so

### ISSUE THREAD

**Issue by dummied** [tiy-indianapolis-ror-june2015/AlecDanny-Week6Lab#51]
https://github.com/tiy-indianapolis-ror-june2015/AlecDanny-Week6Lab/blob/master/app/controllers/posts_controller.rb#L48

Right now, I can edit anybody's post. Find from current_user.posts instead of plain olde Post.

**Comment by dummied** [comment]
Same with destroy: https://github.com/tiy-indianapolis-ror-june2015/AlecDanny-Week6Lab/blob/master/app/controllers/posts_controller.rb#L61

Right now, I could delete _anybody's_ post.

**Comment by dummied** [comment]
Same with profiles.

**Comment by beyrerdn** [comment]
Removed CRUD from Profiles.
